### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by crenspact02**
Now check the preview.

### CODE REVIEW

**Review by Anshul1507 — COMMENTED** [review]
You should also check the preview once. Is it looking good according to yours?

**Comment by crenspact02** [comment]
Yes, I guess now it looks well enough.

**Comment by Anshul1507** [comment]
Lets give chance to others, maybe someone can understand the exact issue. 

NLGTM! (Not Looking Good To Me)

**Comment by crenspact02** [comment]
No Problem!

**Pull request closed without merging**
